version: '3'

services:
  reverse-proxy:
    container_name: reverse-proxy
    build: 
      context: ./reverse_proxy
    volumes:
      - ./reverse_proxy/nginx.conf:/var/www/html
      - ./reverse_proxy/nginx.conf:/etc/nginx/sites-available/default
    depends_on:
      - fast-backend
    ports:
      - 80:80
      - 443:443

  react-frontend:
    image: react-frontend
    container_name: react-frontend
    build:
      context: ./react_frontend
    ports:
      - 8002:8002
    restart: on-failure

  fast-backend:
    image: fast-backend
    container_name: fast-backend
    build:
      context: ./fast_backend
    ports:
      - 8001:8001
    restart: on-failure